"""
Auto-generated by the Urutau GUI on 2026-09-16 09:08.

Standalone script: reproduces, outside the GUI, exactly the pipeline that
was configured in it. Safe to edit by hand and re-run (e.g. on a cluster).
"""

from urutau import Urutau
from urutau.modules import (
    CcmLaw,
    DegradeDataFlex,
    SNMaskWithVar,
    SpectralResampler,
    StarlightOnUrutau,
)


def run():
    urutau = Urutau(num_threads=1)

    cfg_1 = {
        'hdu target': 'DATA',
        'input type': 'R',
        'input value': 3027.0,
        'output type': 'FWHM',
        'output value': 2.51,
        'data type': 'flux',
    }
    urutau.add_module(DegradeDataFlex, cfg_1)

    cfg_2 = {
        'hdu target': 'STAT',
        'input type': 'R',
        'input value': 3027.0,
        'output type': 'FWHM',
        'output value': 2.51,
        'data type': 'variance',
    }
    urutau.add_module(DegradeDataFlex, cfg_2)

    cfg_3 = {
        'hdu target': 'DATA_DEGR',
        'data type': 'flux',
        'resample size': 1.0,
    }
    urutau.add_module(SpectralResampler, cfg_3)

    cfg_4 = {
        'hdu target': 'STAT_DEGR',
        'data type': 'variance',
        'resample size': 1.0,
    }
    urutau.add_module(SpectralResampler, cfg_4)

    cfg_5 = {
        'hdu flux': 'DATA_DEGR_BIN',
        'ebv': 0.0,
        'rv': 3.1,
    }
    urutau.add_module(CcmLaw, cfg_5)

    cfg_6 = {
        'hdu flux': 'FLUX_DRD',
        'sn window': (5650.0, 5750.0),
        'thresholds': [10, 20],
        'redshift': 0.0,
        'hdu var': 'STAT_DEGR_BIN',
    }
    urutau.add_module(SNMaskWithVar, cfg_6)

    cfg_7 = {
        'starlight path': '/disk3/BASS_CUBES/starlight/StarlightChains_v04.amd64_g77-3.4.6-r1_static.exe',
        'default grid file': '/disk3/BASS_CUBES/starlight/reference_grid_muse_newMiles.in',
        'hdu flux': 'FLUX_DRD',
        'number of threads': 52,
        'population ages': {'xyy': (100.0, 10100000.0), 'xyo': (10100000.0, 56300000.0), 'xiy': (56300000.0, 502000000.0), 'xy': (100.0, 56300000.0), 'xii': (502000000.0, 795000000.0), 'xio': (795000000.0, 2010000000.0), 'xi': (56300000.0, 2010000000.0), 'xo': (2010000000.0, 13000000000.0)},
        'galaxy distance': 0.0,
        'redshift': 0.0,
        'normalization factor': 1.0,
        'flux unit': '',
        'keep tmp': False,
        'timeout mode': 'adaptive',
        'timeout minutes': 15.0,
        'timeout window': 15,
        'timeout multiplier': 3.0,
        'ret mass ages': {'inter': (10.0, 2000000000.0)},
        'fc exps': {'FC_50': (0.49, 0.51)},
        'hdu var': 'STAT_DEGR_BIN',
        'hdu flag': 'SN_MASKS_10',
    }
    urutau.add_module(StarlightOnUrutau, cfg_7)

    # Load targets
    urutau.read_csv(targets_dir='/disk3/BASS_CUBES/muse_cubes/', csv_file='/disk3/BASS_CUBES/muse_cubes/targets_OP_BASS_27_lais_mask.csv')

    # Execute urutau
    urutau.execute('/disk3/BASS_CUBES/run_urutau_Aug_26_up8850_ntel_new_retmass/', save_config=True, debug=True, overwrite=False)


if __name__ == "__main__":
    run()
