# Importing the urutau class
from urutau import Urutau

# Importing all the relevant modules
from urutau.modules import (
    SpatialResampler,
    SpectralResampler,
    DegradeDataFlex,
    CcmLaw,
    SNMaskWithVar,
    StarlightOnUrutau
)


def MUSE():

    # Open urutau (with two threads to process data)
    urutau = Urutau(num_threads=1)

    # First degrade resolving power for the data hdu (MUSE R=3027 -> MILES FWHM=2.51 A)
    data_degrade_cfg = {
        "hdu target": "DATA",
        "data type": "flux",
        "input type": "R",
        "input value": 3027,
        "output type": "FWHM",
        "output value": 2.51,
    }
    urutau.add_module(DegradeDataFlex, data_degrade_cfg)

    # Second degrade resolving power for the stat hdu (MUSE R=3027 -> MILES FWHM=2.51 A)
    stat_degrade_cfg = {
        "hdu target": "STAT",
        "data type": "variance",
        "input type": "R",
        "input value": 3027,
        "output type": "FWHM",
        "output value": 2.51,
    }
    urutau.add_module(DegradeDataFlex, stat_degrade_cfg)

    # First spectral resampler for the degraded data hdu
    data_spec_resample_cfg = {
        "hdu target": "DATA_DEGR",
        "data type": "flux",
        "resample size": 1.
    }
    urutau.add_module(SpectralResampler, data_spec_resample_cfg)

    # Second spectral resampler for the degraded stat hdu
    stat_spec_resample_cfg = {
        "hdu target": "STAT_DEGR",
        "data type": "variance",
        "resample size": 1.
    }
    urutau.add_module(SpectralResampler, stat_spec_resample_cfg)

    # Add each module in SEQUENCE of execution
    # CcmLaw
    ccm_cfg = {"hdu flux": "DATA_DEGR_BIN"}
    urutau.add_module(CcmLaw, ccm_cfg)

    # SNMaskWithVar MODULE
    sn_mask_cfg = {
        "hdu flux": "FLUX_DRD",
        "hdu var": "STAT_DEGR_BIN",
        "sn window": (5650, 5750),
        "thresholds": [10, 20]
    }
    urutau.add_module(SNMaskWithVar, sn_mask_cfg)

    # StarlightOnUrutau MODULE
    #
    # Creating a dictionary with the desired population vectors and their
    # age limits (min, max) to be used with the starlight configuration
    pop_age_par = {
        
        "xyy": (100, 10.1E6),
        "xyo": (10.1E6, 56.3E6),
        "xiy": (56.3E6, 502.0E6),
        "xy": (100, 56.3E6),
        "xii": (502.0E6, 795.0E6),
        "xio": (795.0E6, 2.01E9),
        "xi": (56.3E6, 2.01E9),
        "xo": (2.01E9, 13E9)
    }
    
    # define AGN parameters (see RIffel+09 and Riffel+22)
    fc_par = {
        "FC_50": (0.49, 0.51)
    }

    # define returned mass age limits (ages <= 2.E9 as in getRetMass.py)
    ret_mass_par = {
        "inter": (10., 2.0E9),
    }

    # Using the flux hdu generated by CcmLaw ("FLUX_DRD") and the mask hdu
    # generated by the SignalToNoiseMask ("FN_MASKS_10") as the flag
    # for bad spaxels
    #
    # Setting up the path to the starlight static executable and a reference
    # grid (see Cid Fernandes' starlight manual) as well as the population ages
    #
    # Obs: the reference grid must contain at least 1 mock target line (see
    #      example "reference_grid.in")
    starlight_cfg = {
        "starlight path": "./starlight/StarlightChains_v04.amd64_g77-3.4.6-r1_static.exe",
        "default grid file": "./starlight/reference_grid_muse_newMiles.in",
        "hdu flux": "FLUX_DRD",
        "hdu var": "STAT_DEGR_BIN",
        "hdu flag": "SN_MASKS_10",
        "number of threads": 52,
        "population ages": pop_age_par,
        "ret mass ages": ret_mass_par,
        "fc exps": fc_par,
    }
    urutau.add_module(StarlightOnUrutau, starlight_cfg)

        # Load targets
    urutau.read_csv(targets_dir="./muse_cubes/", csv_file="./muse_cubes/targets_OP_BASS_27_lais.csv")


    # Execute urutau
    # If save_config is true, urutau will append a configuration hdu to every
    # resulting datacube with the relevant configuration parameters
    urutau.execute("./run_urutau_Aug_26_up8850_ntel_new_retmass/", save_config=True, debug=True)

if __name__=="__main__":
    MUSE()
