"""
script_export.py — Renders a GUI configuration as a standalone, GUI-free
Python script that reproduces the exact same Urutau pipeline, so it can be
run by hand (e.g. on a cluster with no display) without touching the GUI.
"""

from datetime import datetime

from .urutau_wrapper import build_module_chain

# Module class name -> the actual module it must be imported from.
# Most modules are re-exported from urutau.modules; CalzettiLaw/Fitzpatrick
# are not (yet), so they're imported from their private submodule directly
# — same as urutau_wrapper.py does.
_MODULE_IMPORT_SOURCE = {
    "SpatialResampler": "urutau.modules",
    "SpectralResampler": "urutau.modules",
    "DegradeDataFlex": "urutau.modules",
    "CcmLaw": "urutau.modules",
    "SeatonLaw": "urutau.modules",
    "SNMaskWithVar": "urutau.modules",
    "SNMaskWithError": "urutau.modules",
    "SNMaskWithIVar": "urutau.modules",
    "SNMaskMeanStd": "urutau.modules",
    "StarlightOnUrutau": "urutau.modules",
    "CalzettiLaw": "urutau.modules._dereddening",
    "Fitzpatrick": "urutau.modules._dereddening",
}


def _render_imports(chain: list) -> str:
    by_source = {}
    for module_cls, _ in chain:
        name = module_cls.__name__
        source = _MODULE_IMPORT_SOURCE.get(name, "urutau.modules")
        by_source.setdefault(source, set()).add(name)

    lines = ["from urutau import Urutau"]
    for source in sorted(by_source):
        names = sorted(by_source[source])
        if len(names) == 1:
            lines.append(f"from {source} import {names[0]}")
        else:
            names_block = ",\n    ".join(names)
            lines.append(f"from {source} import (\n    {names_block},\n)")
    return "\n".join(lines)


def _render_dict_literal(d: dict, key_indent: str = "        ", close_indent: str = "    ") -> str:
    lines = ["{"]
    for key, value in d.items():
        lines.append(f"{key_indent}{key!r}: {value!r},")
    lines.append(f"{close_indent}}}")
    return "\n".join(lines)


def _render_module_calls(chain: list) -> str:
    lines = []
    for i, (module_cls, module_cfg) in enumerate(chain, start=1):
        var_name = f"cfg_{i}"
        lines.append(f"    {var_name} = {_render_dict_literal(module_cfg)}")
        lines.append(f"    urutau.add_module({module_cls.__name__}, {var_name})")
        lines.append("")
    return "\n".join(lines).rstrip("\n")


def generate_script(cfg: dict) -> str:
    """Renders cfg as standalone Python source (same pipeline as run_pipeline(cfg))."""
    chain = build_module_chain(cfg)
    targets = cfg["targets"]
    out = cfg["output"]

    parts = [
        '"""',
        f"Auto-generated by the Urutau GUI on {datetime.now():%Y-%m-%d %H:%M}.",
        "",
        "Standalone script: reproduces, outside the GUI, exactly the pipeline that",
        "was configured in it. Safe to edit by hand and re-run (e.g. on a cluster).",
        '"""',
        "",
        _render_imports(chain),
        "",
        "",
        "def run():",
        f"    urutau = Urutau(num_threads={cfg.get('num_threads', 1)})",
        "",
        _render_module_calls(chain),
        "",
        "    # Load targets",
        f"    urutau.read_csv(targets_dir={targets['dir']!r}, csv_file={targets['csv']!r})",
        "",
        "    # Execute urutau",
        f"    urutau.execute({out['save_path_root']!r}, "
        f"save_config={out['save_config']!r}, debug={out['debug']!r}, "
        f"overwrite={out.get('overwrite', True)!r})",
        "",
        "",
        'if __name__ == "__main__":',
        "    run()",
        "",
    ]
    return "\n".join(parts)
